name: docker

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  docker:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: emizzle/nim-codex-arm64
          tags: |
            type=semver,pattern={{version}}
            type=sha
      # - name: Show tags
      #   run: echo "${{ steps.meta.outputs.tags }}"
      # - name: Show labels
      #   run: echo "${{ steps.meta.outputs.labels }}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/codex.Dockerfile
          platforms: linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      # Slim it!
      - name: Minify docker image
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: ${{ steps.meta.outputs.tags }}
          tag: "slim"
      - name: Show slim report
        run: echo "${{ steps.slim.outputs.report }}"
      # Push to the docker registry
      - name: Push image to docker registry
        run: docker image push "${{ steps.meta.outputs.tags }}"
        if: github.event_name != 'pull_request'
